### ISSUE TITLE
UnicodeDecodeError in Tutorial

### ISSUE THREAD

**Issue by adityaxbiswas** [marcotcr/lime#15]
I tried following the iris dataset tutorial verbatim, and I'm getting the following when I call the show_in_notebook method:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda2\envs\ML\lib\site-packages\lime\explanation.py", line 139, in show_in_notebook
    display(HTML(self.as_html(labels, predict_proba, **kwargs)))
  File "D:\Anaconda2\envs\ML\lib\site-packages\lime\explanation.py", line 171, in as_html
    bundle = open(os.path.join(this_dir, 'bundle.js')).read()
  File "D:\Anaconda2\envs\ML\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 58267: character maps to <undefined>

**Comment by marcotcr** [comment]
Argh, I'm sorry. Could you tell me which version of python you have? Also, which version of LIME are you using, and what OS?
Thanks,

**Comment by adityaxbiswas** [comment]
Python 3.5.1, LIME 0.1.1.13, Windows Server 2012 R2 Standard

Thanks for your help.

**Comment by marcotcr** [comment]
I can't replicate the error on Python 3 on mac OS. I pushed a new version (1.1.14) with an updated bundle.js anyway, would you mind upgrading and letting me know if that fixed the issue?
Thanks,

**Comment by adityaxbiswas** [comment]
I've tried upgrading to LIME 0.1.1.14 and Python 3.5.2 as well as uninstalling and reinstall numpy, scipy, scikit-learn, and ipython.  

It's still throwing the same error, except the byte position changed to 59286.

**Comment by marcotcr** [comment]
Would you mind trying 0.1.1.15? I haven't installed a windows VM yet to try it, but I think I fixed it.

**Comment by adityaxbiswas** [comment]
Yes, it now works!  Thanks for your quick help
